import type { Metadata } from "next";
import { Provider } from "@/components/ui/provider";
import Header from "@/components/ui/Header";
import { Box } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className="dark" suppressHydrationWarning>
      <body>
        <Provider>
          <Header />
          <Box margin="auto" maxW="1200px">{children}</Box>
        </Provider>
      </body>
    </html>
  );
}
